# Generated by Django 5.1.6 on 2025-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='desciption',
            field=models.TextField(),
        ),
    ]
