# Generated by Django 5.1.6 on 2025-02-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_photo_desciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pictures.categories'),
        ),
    ]
